import { FeatureTab } from "../../../types/assets/featureTab";

const featuresTabData: FeatureTab[] = [
  {
    id: "tabOne",
    title: "CPD Management",
    desc1: `A CDP allows you to leverage your most precious assets to borrow stablecoins, in our case $XOC. You can use XOC to buy more assets, pay off debt, or whatever you want.`,
    desc2: `$XOC is ERC20 so it is also compatible with the DeFi ecosystem. You can use it to create Liquidity Pools, farm yield or even use it as collateral for other loans.`,
    image: "/Currency Crush - Profit.svg",
    imageDark: "/Currency Crush - Profit.svg",
    button: "Mint $XOC",
    link: "/cdp",
  },
  {
    id: "tabTwo",
    title: "Money Lending Markets",
    desc1: `Our money markets are a fork of the Aave contracts, which are the most battle-tested and resilient smart contracts in DeFi. We have deployed our contracts on the most popular L2 networks, including Arbitrum, Base, Ethereum Mainnet, Polygon, Optimism, Gnosis Chain, and more.`,
    desc2: `You can lend your $XOC to earn interest or borrow $XOC by providing collateral. The interest rates are determined by the supply and demand of the market.`,
    image: "/Currency Crush - Loan.svg",
    imageDark: "/Currency Crush - Loan.svg",
    button: "Lend $XOC",
    link: "lending",
  },
  {
    id: "tabThree",
    title: "Liquidity Providing",
    desc1: `Providing liquidity allows you to earn fees by supplying your $XOC to liquidity pools. These pools facilitate trading on decentralized exchanges.`,
    desc2: `By adding your $XOC to a liquidity pool, you can earn a share of the trading fees generated by the pool. This is a great way to put your assets to work and earn passive income.`,
    image: "/Currency Crush - Liquidity.svg",
    imageDark: "/Currency Crush - Growth.svg",
    button: "Provide Liquidity",
    link: "/liquidity",
  },
];

export default featuresTabData;
