export const mockDepinscanMetrics = [
    {
        date: "2024-12-17",
        total_projects: "291",
        market_cap: "36046044620.57570635160",
        total_device: "19416950",
    },
];

export const mockDepinscanProjects = [
    {
        project_name: "Solana",
        slug: "solana",
        logo: "https://depinscan-prod.s3.us-east-1.amazonaws.com/next-s3-uploads/3160a9ec-42df-4f02-9db6-5aadc61323d8/solana.svg",
        description:
            "Solana is a general purpose layer 1 blockchain that works well for DePIN (decentralized physical infrastructure Network) projects due to its low transaction cost, high-throughput speed, scalability and existing Solana DePIN ecosystem. The most renowned Solana DePIN projects include Helium, Hivemapper and Render.",
        trusted_metric: true,
        token: "SOL",
        layer_1: ["Solana"],
        categories: ["Chain"],
        market_cap: "106247097756.0147",
        token_price: "221.91",
        total_devices: 0,
        network_status: "Mainnet",
        avg_device_cost: "",
        days_to_breakeven: "",
        estimated_daily_earnings: "",
        chainid: "",
        coingecko_id: "solana",
        fully_diluted_valuation: "131508718985",
    },
    {
        project_name: "Render",
        slug: "render",
        logo: "https://depinscan-prod.s3.amazonaws.com/depin/9e5f0bb330344d580b9e30d338d6ab6d.png",
        description:
            "Render is a decentralized rendering platform supporting next-generation media production.",
        trusted_metric: true,
        token: "RNDR",
        layer_1: ["Solana"],
        categories: ["Server", "AI"],
        market_cap: "4659773671.856073",
        token_price: "9.02",
        total_devices: 0,
        network_status: "Mainnet",
        avg_device_cost: "",
        days_to_breakeven: "",
        estimated_daily_earnings: "",
        chainid: "1",
        coingecko_id: "render-token",
        fully_diluted_valuation: "4705509105",
    },
];

export const parsedProjectsSample = [
    [
        "project_name",
        "slug",
        "token",
        "layer_1",
        "categories",
        "market_cap",
        "token_price",
        "total_devices",
        "avg_device_cost",
        "days_to_breakeven",
        "estimated_daily_earnings",
        "chainid",
        "coingecko_id",
        "fully_diluted_valuation",
    ],
    [
        "Solana",
        "solana",
        "SOL",
        "Solana",
        "Chain",
        "106.25B",
        "221.91",
        "0",
        "",
        "",
        "",
        "",
        "solana",
        "131.51B",
    ],
    [
        "Render",
        "render",
        "RNDR",
        "Solana",
        "Server, AI",
        "4.66B",
        "9.02",
        "0",
        "",
        "",
        "",
        "1",
        "render-token",
        "4.71B",
    ],
];
